### ISSUE TITLE
咋样才能取得像yolov8-obb那样80的map啊?

### ISSUE THREAD

**Issue by B1SH0PP** [kuazhangxiaoai/yolov8-obb#3]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

您好, 请问个问题, DOTA数据集的map用数据集官方的测试脚本测出来的和直接用yolov8给出的map不一样吗? 这二者的map差距很大吗?
我自己从头训练了300轮, yolov8s-obb的map才58? 我有点疑惑, 咋样才能取得像yolov8-obb那样80的map啊?

这是我的超参:
![image](https://github.com/kuazhangxiaoai/yolov8-obb/assets/79520631/077aefa2-0736-40c1-a8e3-f4139eca3d71)
![image](https://github.com/kuazhangxiaoai/yolov8-obb/assets/79520631/b8e5cf19-7519-4637-9ca8-698f5d02b19f)

@

**Comment by B1SH0PP** [comment]
@kuazhangxiaoai

**Comment by kuazhangxiaoai** [comment]
@B1SH0PP 您用DOTA官方的工具DOTA_devkit对数据进行切割了么？

**Comment by B1SH0PP** [comment]
@kuazhangxiaoai 
没有, 我试试看, 感谢!
您的超参可以分享下吗, 我做个参考, 万分感谢.

**Comment by kuazhangxiaoai** [comment]
@B1SH0PP 
参数文件：https://github.com/kuazhangxiaoai/yolov8-obb/blob/main/ultralytics/cfg/default.yaml
你用我的代码，别用官方的了，我这边的代码是适配过的。

**Comment by B1SH0PP** [comment]
感谢!
